export enum FORMULAIRE_EMIT_EVENT {
    REFRESH = 'REFRESH'
}

export enum FORMULAIRE_QUESTION_EMIT_EVENT {
    DUPLICATE = 'DUPLICATE',
    DELETE = 'DELETE',
    UNDO = 'UNDO'
}

export enum FORMULAIRE_BROADCAST_EVENT {
    DISPLAY_FILES = 'DISPLAY_FILES',
    INIT_CONTROLLER = 'INIT_CONTROLLER'
}