export enum FORMULAIRE_EMIT_EVENT {
    REFRESH = 'REFRESH'
}

export enum FORMULAIRE_QUESTION_EMIT_EVENT {
    DUPLICATE = 'DUPLICATE',
    DELETE = 'DELETE',
    UNDO = 'UNDO'
}

export enum FORMULAIRE_BROADCAST_EVENT {
    DISPLAY_FILES = 'DISPLAY_FILES',
    INIT_FORM_EDITOR = 'INIT_FORM_EDITOR',
    INIT_FORM_PROP = 'INIT_FORM_PROP',
    INIT_FORM_RESULTS = 'INIT_FORM_RESULTS',
    INIT_RECAP_QUESTIONS = 'INIT_RECAP_QUESTIONS',
    INIT_RESPOND_QUESTION = 'INIT_RESPOND_QUESTION'
}