export enum FORMULAIRE_EMIT_EVENT {
    REFRESH = 'REFRESH',
    UPDATE_FOLDER = 'UPDATE_FOLDER'
}

export enum FORMULAIRE_FORM_ELEMENT_EMIT_EVENT {
    DUPLICATE = 'DUPLICATE',
    DELETE = 'DELETE',
    UNDO = 'UNDO',
    VALIDATE = 'VALIDATE',
    CREATE = 'CREATE'
}

export enum FORMULAIRE_BROADCAST_EVENT {
    DISPLAY_FILES = 'DISPLAY_FILES',
    INIT_FORM_EDITOR = 'INIT_FORM_EDITOR',
    INIT_FORM_PROP = 'INIT_FORM_PROP',
    INIT_FORM_RESULTS = 'INIT_FORM_RESULTS',
    INIT_RECAP_QUESTIONS = 'INIT_RECAP_QUESTIONS',
    INIT_RESPOND_QUESTION = 'INIT_RESPOND_QUESTION',
    INIT_RGPD_QUESTION = 'INIT_RGPD_QUESTION'
}