GRANT USAGE ON SCHEMA formulaire TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA formulaire TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA formulaire TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA formulaire TO "apps";